@grid: 20px;
@gridMobile: 10px;
@import '~mesaic-client/styles/breakpoints.less';

// helper functions
// HORIZONTAL

.paddingHorizontal(@factor) {
  padding-left: (@grid * @factor);
  padding-right: (@grid * @factor);
  .paddingHorizontalMobile(@factor);
}

.paddingHorizontalMobile(@factor) {
  @media @mobile {
    padding-left: (@gridMobile * @factor);
    padding-right: (@gridMobile * @factor);
  }
}

.paddingHorizontalTablet(@factor) {
  @media @tablet {
    padding-left: (@grid * @factor);
    padding-right: (@grid * @factor);
  }
}

.paddingHorizontalDesktop(@factor) {
  @media @desktop {
    padding-left: (@grid * @factor);
    padding-right: (@grid * @factor);
  }
}


// VERTICAL
.paddingVertical(@factor) {
  padding-top: (@grid * @factor);
  padding-bottom: (@grid * @factor);
  .paddingVerticalMobile(@factor);
}

.paddingVerticalMobile(@factor) {
  @media @mobile {
    padding-top: (@gridMobile * @factor);
    padding-bottom: (@gridMobile * @factor);
  }
}

.paddingVerticalTablet(@factor) {
  @media @tablet {
    padding-top: (@grid * @factor);
    padding-bottom: (@grid * @factor);
  }
}

.paddingVerticalDesktop(@factor) {
  @media @desktop {
    padding-top: (@grid * @factor);
    padding-bottom: (@grid * @factor);
  }
}

// TOP
.paddingTop(@factor) {
  padding-top: (@grid * @factor);
  .paddingTopMobile(@factor);
}

.paddingTopMobile(@factor) {
  @media @mobile {
    padding-top: (@gridMobile * @factor);
  }
}

.paddingTopTablet(@factor) {
  @media @tablet {
    padding-top: (@grid * @factor);
  }
}

.paddingTopDesktop(@factor) {
  @media @mobile {
    padding-top: (@gridMobile * @factor);
  }
}

// BOTTOM
.paddingBottom(@factor) {
  padding-bottom: (@grid * @factor);
  .paddingBottomMobile(@factor);
}

.paddingBottomMobile(@factor) {
  @media @mobile {
    padding-bottom: (@gridMobile * @factor);
  }
}

.paddingBottomTablet(@factor) {
  @media @tablet {
    padding-bottom: (@grid * @factor);
  }
}

.paddingBottomDesktop(@factor) {
  @media @desktop {
    padding-bottom: (@grid * @factor);
  }
}


// HORIZONTAL -------------------------------------------------------------------
.h1 { .paddingHorizontal(1) }
.h2 { .paddingHorizontal(2) }
.h3 { .paddingHorizontal(3) }
.h4 { .paddingHorizontal(4) }
.h5 { .paddingHorizontal(5) }
.h8 { .paddingHorizontal(8) }
.h0 { padding-left: 0; padding-right: 0 }

// desktop
.Dh1 { .paddingHorizontalDesktop(1) }
.Dh2 { .paddingHorizontalDesktop(2) }
.Dh3 { .paddingHorizontalDesktop(3) }
.Dh4 { .paddingHorizontalDesktop(4) }
.Dh5 { .paddingHorizontalDesktop(5) }
.Dh8 { .paddingHorizontalDesktop(8) }
.Dh0 { .paddingHorizontalDesktop(0) }

// tablet
.Th1 { .paddingHorizontalTablet(1) }
.Th2 { .paddingHorizontalTablet(2) }
.Th3 { .paddingHorizontalTablet(3) }
.Th4 { .paddingHorizontalTablet(4) }
.Th5 { .paddingHorizontalTablet(5) }
.Th8 { .paddingHorizontalTablet(8) }
.Th0 { .paddingHorizontalTablet(0) }

// mobile
.Mh1 { .paddingHorizontalMobile(1) }
.Mh2 { .paddingHorizontalMobile(2) }
.Mh3 { .paddingHorizontalMobile(3) }
.Mh4 { .paddingHorizontalMobile(4) }
.Mh5 { .paddingHorizontalMobile(5) }
.Mh8 { .paddingHorizontalMobile(8) }
.Mh0 { .paddingHorizontalMobile(0) }

// VERTICAL -------------------------------------------------------------------
.v1 { .paddingVertical(1) }
.v2 { .paddingVertical(2) }
.v3 { .paddingVertical(3) }
.v4 { .paddingVertical(4) }
.v5 { .paddingVertical(5) }
.v8 { .paddingVertical(8) }
.v0 { padding-top: 0; padding-bottom: 0 }

// desktop
.Dv1 { .paddingVerticalDesktop(1) }
.Dv2 { .paddingVerticalDesktop(2) }
.Dv3 { .paddingVerticalDesktop(3) }
.Dv4 { .paddingVerticalDesktop(4) }
.Dv5 { .paddingVerticalDesktop(5) }
.Dv8 { .paddingVerticalDesktop(8) }
.Dv0 { .paddingVerticalDesktop(0) }

// tablet
.Tv1 { .paddingVerticalTablet(1) }
.Tv2 { .paddingVerticalTablet(2) }
.Tv3 { .paddingVerticalTablet(3) }
.Tv4 { .paddingVerticalTablet(4) }
.Tv5 { .paddingVerticalTablet(5) }
.Tv8 { .paddingVerticalTablet(8) }
.Tv0 { .paddingVerticalTablet(0) }

// mobile
.Mv1 { .paddingVerticalMobile(1) }
.Mv2 { .paddingVerticalMobile(2) }
.Mv3 { .paddingVerticalMobile(3) }
.Mv4 { .paddingVerticalMobile(4) }
.Mv5 { .paddingVerticalMobile(5) }
.Mv8 { .paddingVerticalMobile(8) }
.Mv0 { .paddingVerticalMobile(0) }

// TOP -------------------------------------------------------------------

.t1 { .paddingTop(1) }
.t2 { .paddingTop(2) }
.t3 { .paddingTop(3) }
.t4 { .paddingTop(4) }
.t5 { .paddingTop(5) }
.t8 { .paddingTop(8) }
.t0 { .paddingTop(0) }

// desktop
.Dt1 { .paddingTopDesktop(1) }
.Dt2 { .paddingTopDesktop(2) }
.Dt3 { .paddingTopDesktop(3) }
.Dt4 { .paddingTopDesktop(4) }
.Dt5 { .paddingTopDesktop(5) }
.Dt8 { .paddingTopDesktop(8) }
.Dt0 { .paddingTopDesktop(0) }

// tablet
.Tt1 { .paddingTopTablet(1) }
.Tt2 { .paddingTopTablet(2) }
.Tt3 { .paddingTopTablet(3) }
.Tt4 { .paddingTopTablet(4) }
.Tt5 { .paddingTopTablet(5) }
.Tt8 { .paddingTopTablet(8) }
.Tt0 { .paddingTopTablet(0) }

// mobile
.Mt1 { .paddingTopMobile(1) }
.Mt2 { .paddingTopMobile(2) }
.Mt3 { .paddingTopMobile(3) }
.Mt4 { .paddingTopMobile(4) }
.Mt5 { .paddingTopMobile(5) }
.Mt8 { .paddingTopMobile(8) }
.Mt0 { .paddingTopMobile(0) }

// BOTTOM -------------------------------------------------------------------

.b1 { .paddingBottom(1) }
.b2 { .paddingBottom(2) }
.b3 { .paddingBottom(3) }
.b4 { .paddingBottom(4) }
.b5 { .paddingBottom(5) }
.b8 { .paddingBottom(8) }
.b0 { .paddingBottom(0) }

// Desktop
.Db1 { .paddingBottomDesktop(1) }
.Db2 { .paddingBottomDesktop(2) }
.Db3 { .paddingBottomDesktop(3) }
.Db4 { .paddingBottomDesktop(4) }
.Db5 { .paddingBottomDesktop(5) }
.Db8 { .paddingBottomDesktop(8) }
.Db0 { .paddingBottomDesktop(0) }

// Tablet
.Tb1 { .paddingBottomTablet(1) }
.Tb2 { .paddingBottomTablet(2) }
.Tb3 { .paddingBottomTablet(3) }
.Tb4 { .paddingBottomTablet(4) }
.Tb5 { .paddingBottomTablet(5) }
.Tb8 { .paddingBottomTablet(8) }
.Tb0 { .paddingBottomTablet(0) }

// Mobile
.Mb1 { .paddingBottomMobile(1) }
.Mb2 { .paddingBottomMobile(2) }
.Mb3 { .paddingBottomMobile(3) }
.Mb4 { .paddingBottomMobile(4) }
.Mb5 { .paddingBottomMobile(5) }
.Mb8 { .paddingBottomMobile(8) }
.Mb0 { .paddingBottomMobile(0) }

 // NONE
.n { padding: 0 }
